### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [cepdnaclk/e16-3yp-computerized-timetabling-and-attendance-marking-system#46]
Hi,<br><br>url : https://github.com/cepdnaclk/e16-3yp-computerized-timetabling-and-attendance-marking-system/blob/c826ff89f312542a011ff00d1b8dc458a6acff96/API/src/main/resources/application.properties.txt <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by NuwanHarsha** [comment]
Thanks,for pointing it out.I just removed it.😀

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
